### ISSUE TITLE
Add responsive design

### ISSUE THREAD

**Issue by pasca-l** [pasca-l/portfolio#1]
- [x] Widen `textbody`, if the browser width is small
- [x] Fix `top_image` text, for any browser width 
- [x] Make hamburger menu, if the browser width is small

**Comment by abitsalihu** [comment]
Hey @pasca-l, I would like to work on this issue. :)

**Comment by pasca-l** [comment]
@abitsalihu I am already working on this issue right now (forgot to assign this to myself), but thanks for your offer👍
